.template_repo: &repo
  project: &ci_tmpl 'devops/ci/templates'
  ref: &ci_tmpl_vers 'v3.7.1'

.template_deb_build:
  image: harbor.wildberries.ru/swarm/swarm/swarmops/docker-factory/deb-builder:feature-golang-deb-image-15393609

  after_script:
    - |
      STRIPPED_VERSION="${CI_COMMIT_TAG#v}"
        if [ -z "$STRIPPED_VERSION" ]; then
        STRIPPED_VERSION="${VERSION}"
        fi
    - mkdir -p ./${PACKAGE}_${STRIPPED_VERSION}_amd64/usr/local/bin
    - mkdir -p ./${PACKAGE}_${STRIPPED_VERSION}_amd64/DEBIAN
    - sed -i deploy/${PACKAGE}/control -e "s/version/${STRIPPED_VERSION}/"
    - cp bin/${PACKAGE} ${PACKAGE}_${STRIPPED_VERSION}_amd64/usr/local/bin/${PACKAGE}
    - cp deploy/${PACKAGE}/control ${PACKAGE}_${STRIPPED_VERSION}_amd64/DEBIAN/control
    - dpkg-deb --root-owner-group --build ./${PACKAGE}_${STRIPPED_VERSION}_amd64
    - 'curl -u "${NEXUS_USER}:${NEXUS_PASSWORD}" -H "Content-Type: multipart/form-data" --data-binary "@./${PACKAGE}_${STRIPPED_VERSION}_amd64.deb" "${NEXUS_URL}/${NEXUS_REPO}/"'
  tags:
    - dev
    - docker
    - linux

default:
  tags:
    - swarm

variables:
  # Mandatory vars. Do not change this
  CI_TMPL_PROJECT: *ci_tmpl
  CI_TMPL_PROJECT_VERSION: *ci_tmpl_vers
  #
  # Language specific vars. Most likly need to specify
  #
  APP_VER: "1.0.4"
  BUILD_CUSTOM_ARGS: "APP_VER=${APP_VER},TERRAFORM_VER=1.6.3"
  GO_MAIN_PATH: ./app
  GO_VER: "1.20"
  ALPINE_VER: "3.17"
  GO_TEST_FLAGS: "-mod=readonly"

  JOB_ID: "$CI_JOB_ID"

  CI_TMPL_HELM_CHARTS: "common-deploy@v4.2.0,common-job"
  CI_TMPL_HELM_CHART_COMMON_JOB_VERSION: 1.0.2
  CI_TMPL_HELM_RELEASE_NAMESPACE: swarm
  # List of clusters for deploy
  # CI_TMPL_KUBE_CLUSTERS_DEV: "k8s.dldevel"
  CI_TMPL_KUBE_CLUSTERS_DEV: "k8s.hbf-bm"
  CI_TMPL_KUBE_CLUSTERS_STAGE: ""
  CI_TMPL_KUBE_CLUSTERS_PROD: "k8s.prod-dl,k8s.prod-dp"
  
  CI_TMPL_HELM_CUSTOM_TG_TOKEN: "$TG_TOKEN"
  CI_TMPL_HELM_CUSTOM_TG_GROUP_ID: "$TG_GROUP_ID"
  CI_TMPL_HELM_CUSTOM_CI_PIPELINE_ID: "$CI_PIPELINE_ID"
  CI_TMPL_HELM_CUSTOM_CI_JOB_ID: "$JOB_ID"
  CI_TMPL_HELM_CUSTOM_CI_SOURCE_BRANCH_NAME: "$CI_COMMIT_BRANCH"
  CI_TMPL_HELM_CUSTOM_COMMIT: "$CI_COMMIT_SHORT_SHA"
  # Harbor project name
  REGISTRY_PROJECT: "swarm"

  # Change deploy jobs appearance in pipeline
  CI_TMPL_DEPLOY_GROUPING: per-service

  MAJOR_VERSION: 1
  NEXUS_URL: http://swarm-nexus-ingress-controller.swarm-nexus.svc.k8s.prod-dl/repository
  NEXUS_REPO: swarm-apt-hosted

include:
  - <<: *repo
    file: /global.yml
  - <<: *repo
    file: /checks.yml
  - <<: *repo
    file: /go/global.yml
  - <<: *repo
    file: /docker/build.yml
  - <<: *repo
    file: /helm/deploy.yml

stages:
  - checks
  - generate dynamic pipeline
  - build
  - deploy
  - check approve

sgroups-deb:
  stage: build
  extends: .template_deb_build
  script:
    - make sg-service platform=linux/amd64
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^feature-.*$/ || $CI_COMMIT_BRANCH =~ /^dev$/
      variables:
        VERSION: $MAJOR_VERSION-$CI_COMMIT_BRANCH
    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        VERSION: $CI_COMMIT_TAG

  variables:
    PACKAGE: sgroups

to-nft-deb:
  stage: build
  extends: .template_deb_build
  script:
    - make to-nft platform=linux/amd64
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^feature-.*$/ || $CI_COMMIT_BRANCH =~ /^dev$/
      variables:
        VERSION: $MAJOR_VERSION-$CI_COMMIT_BRANCH
    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        VERSION: $CI_COMMIT_TAG
  variables:
    PACKAGE: to-nft

generate build:
  variables:
    CI_TMPL_HELM_RELEASE_NAMES: "sgroups,sgroups-arm64,to-nft-arm64,to-nft,sgroups-migration,terraform-provider-sgroups-v2,documentation"

generate deploy:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^dev$/
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "aba-control@common-job"

    - if: $CI_COMMIT_BRANCH =~ /^feature-.*$/
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "aba-control@common-job"

    - if: $CI_COMMIT_BRANCH =~ /^feature-docs-.*$/
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "documentation"

    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "sgroups,documentation"
