.template_repo: &repo
  project: &ci_tmpl 'devops/ci/templates'
  ref: &ci_tmpl_vers 'v3.7.1'

variables:
  # Mandatory vars. Do not change this
  CI_TMPL_PROJECT: *ci_tmpl
  CI_TMPL_PROJECT_VERSION: *ci_tmpl_vers

  #
  # Language specific vars. Most likly need to specify
  # 
  GO_MAIN_PATH: ./app
  GO_VER: "1.20"
  ALPINE_VER: "3.17"
  GO_TEST_FLAGS: "-mod=readonly"

  JOB_ID: "$CI_JOB_ID"

  CI_TMPL_HELM_CHARTS: "common-deploy@v4.2.0,common-job"
  CI_TMPL_HELM_CHART_COMMON_JOB_VERSION: 1.0.2
  CI_TMPL_HELM_RELEASE_NAMESPACE: swarm
  # List of clusters for deploy
  # CI_TMPL_KUBE_CLUSTERS_DEV: "k8s.dldevel"
  CI_TMPL_KUBE_CLUSTERS_DEV: "k8s.hbf-bm"
  CI_TMPL_KUBE_CLUSTERS_STAGE: ""
  CI_TMPL_KUBE_CLUSTERS_PROD: "k8s.prod-dl,k8s.prod-dp"
  
  CI_TMPL_HELM_CUSTOM_TG_TOKEN: "$TG_TOKEN"
  CI_TMPL_HELM_CUSTOM_TG_GROUP_ID: "$TG_GROUP_ID"
  CI_TMPL_HELM_CUSTOM_CI_PIPELINE_ID: "$CI_PIPELINE_ID"
  CI_TMPL_HELM_CUSTOM_CI_JOB_ID: "$JOB_ID"
  CI_TMPL_HELM_CUSTOM_CI_SOURCE_BRANCH_NAME: "$CI_COMMIT_BRANCH"
  CI_TMPL_HELM_CUSTOM_COMMIT: "$CI_COMMIT_SHORT_SHA"

  # Harbor project name
  REGISTRY_PROJECT: "swarm"

  # Change deploy jobs appearance in pipeline
  CI_TMPL_DEPLOY_GROUPING: per-service

include:
  - <<: *repo
    file: /global.yml
  - <<: *repo
    file: /checks.yml
  - <<: *repo
    file: /go/global.yml
  - <<: *repo
    file: /docker/build.yml
  - <<: *repo
    file: /helm/deploy.yml

stages:
  - checks
  - generate dynamic pipeline
  - build
  - deploy
  - check approve


generate build:
  tags:
    - swarm
  variables:
    CI_TMPL_HELM_RELEASE_NAMES: "sgroups,to-nft,sgroups-migration,terraform-provider-sgroups"


generate deploy:
  tags:
    - swarm
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^dev$/
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "aba-control@common-job"

    - if: $CI_COMMIT_BRANCH =~ /^feature-.*$/
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "aba-control@common-job"

    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "sgroups"
