.template_repo: &repo
  project: &ci_tmpl 'devops/ci/templates'
  ref: &ci_tmpl_vers 'v3.7.1'
  
.template_deb_build:
  image: harbor.wildberries.ru/swarm/swarm/swarmops/docker-factory/deb-builder:v0-0-8-0ff308cb
  after_script:
    - source deploy/terraform-provider-sgroups-v2/version_setup.sh
    - |
      fpm \
      -n "${PACKAGE}" \
      -s dir \
      -t deb \
      -a "${ARCH}" \
      --license "Apache Software License 2.0" \
      --maintainer "${MAINTAINER}" \
      --description "${DESCRIPTION}" \
      --version "${CUSTOM_VERSION}" \
      bin/${PACKAGE}=/usr/bin/${PACKAGE}
    - ls -lah | grep .deb
    - 'curl -i -u "${NEXUS_USER}:${NEXUS_PASSWORD}" -H "Content-Type: multipart/form-data" --data-binary "@./${PACKAGE}_${CUSTOM_VERSION}_${ARCH}.deb" "${NEXUS_URL}/${NEXUS_REPO}/"'
  
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^feature-.*$/ || $CI_COMMIT_BRANCH =~ /^dev$/
    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
  variables:
    CI_BRANCH: $CI_COMMIT_BRANCH
    CI_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    CI_TAG: $CI_COMMIT_TAG

default:
  tags:
    - dev
    - docker
    - linux

variables:
  # Mandatory vars. Do not change this
  CI_TMPL_PROJECT: *ci_tmpl
  CI_TMPL_PROJECT_VERSION: *ci_tmpl_vers
  #
  # Language specific vars. Most likly need to specify
  #
  BUILD_CUSTOM_ARGS: "CI_TAG=${CI_COMMIT_TAG},CI_BRANCH=${CI_COMMIT_BRANCH},CI_SHORT_SHA=${CI_COMMIT_SHORT_SHA},TERRAFORM_VER=1.6.3"
  GO_MAIN_PATH: ./app
  GO_VER: "1.20"
  ALPINE_VER: "3.17"
  GO_TEST_FLAGS: "-mod=readonly"

  JOB_ID: "$CI_JOB_ID"

  CI_TMPL_HELM_CHARTS: "common-deploy@v4.2.0,common-job"
  CI_TMPL_HELM_CHART_COMMON_JOB_VERSION: 1.0.2
  CI_TMPL_HELM_RELEASE_NAMESPACE: swarm
  # List of clusters for deploy
  # CI_TMPL_KUBE_CLUSTERS_DEV: "k8s.dldevel"
  CI_TMPL_KUBE_CLUSTERS_DEV: "k8s.hbf-bm"
  CI_TMPL_KUBE_CLUSTERS_STAGE: ""
  CI_TMPL_KUBE_CLUSTERS_PROD: "k8s.prod-dl,k8s.prod-dp"
  
  CI_TMPL_HELM_CUSTOM_TG_TOKEN: "$TG_TOKEN"
  CI_TMPL_HELM_CUSTOM_TG_GROUP_ID: "$TG_GROUP_ID"
  CI_TMPL_HELM_CUSTOM_CI_PIPELINE_ID: "$CI_PIPELINE_ID"
  CI_TMPL_HELM_CUSTOM_CI_JOB_ID: "$JOB_ID"
  CI_TMPL_HELM_CUSTOM_CI_SOURCE_BRANCH_NAME: "$CI_COMMIT_BRANCH"
  CI_TMPL_HELM_CUSTOM_COMMIT: "$CI_COMMIT_SHORT_SHA"
  # Harbor project name
  REGISTRY_PROJECT: "swarm"

  # Change deploy jobs appearance in pipeline
  CI_TMPL_DEPLOY_GROUPING: per-service

  NEXUS_URL: http://swarm-nexus-ingress-controller.swarm-nexus.svc.k8s.prod-dl/repository
  NEXUS_REPO: swarm-apt-hosted

  MAINTAINER: "Putilin Dmitry <putilin.dmitriy3@wb.ru>"
  ARCH: amd64

include:
  - <<: *repo
    file: /global.yml
  - <<: *repo
    file: /checks.yml
  - <<: *repo
    file: /go/global.yml
  - <<: *repo
    file: /docker/build.yml
  - <<: *repo
    file: /helm/deploy.yml

stages:
  - checks
  - generate dynamic pipeline
  - build
  - deploy
  - check approve

sgroups-deb:
  stage: build
  extends: .template_deb_build
  script:
    - make sg-service platform=linux/amd64
  variables:
    PACKAGE: sgroups
    DESCRIPTION: HBF-server.

to-nft-deb:
  stage: build
  extends: .template_deb_build
  script:
    - make to-nft platform=linux/amd64
  variables:
    PACKAGE: to-nft
    DESCRIPTION: HBF-agent.

generate build:
  variables:
    CI_TMPL_HELM_RELEASE_NAMES: "sgroups,sgroups-arm64,to-nft-arm64,to-nft,sgroups-migration,terraform-provider-sgroups-v2,documentation"

generate deploy:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^dev$/
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "aba-control@common-job"

    - if: $CI_COMMIT_BRANCH =~ /^feature-.*$/
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "aba-control@common-job"

    - if: $CI_COMMIT_BRANCH =~ /^feature-docs-.*$/
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "documentation"

    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        CI_TMPL_HELM_RELEASE_NAMES: "sgroups,documentation"
