vault:
  enabled: true
  env:
    - services/swarm/prd/swarm-pgsql-cl1/user_admin:
        SG_DB_PASSWORD: password
    - services/swarm/prd/swarm-pgsql-cl1/pgsql_endpoints:
        SG_DB_URL: k8s_haproxy_pgsql_master

  entrypoint: "sh /app/entrypoint.sh"

env:
  SG_DB_USER: user_admin
  SG_DB_NAME: swarm
  SG_STORAGE_TYPE: postgres
