imagePullSecrets:
  - name: harbor-swarm-registry-secret
  - name: harbor-registry-secret

image:
  repository: harbor.wildberries.ru/swarm/swarm/testops/hbf_api_tests/sgroups-postman
  tag: v1-0-4-3119be4e 
  pullPolicy: IfNotPresent

vault:
  enabled: true
  env:
    - services/swarm/dev/swarm-pgsql-cl1-dev/user_admin:
        REPORTER_DB_PWD: password
    - services/swarm/dev/swarm-pgsql-cl1-dev/user_admin:
        REPORTER_DB_HOST_PORT: haproxy_pgsql_allsync_0

  entrypoint: "sh /usr/src/hbf_api_tests/entrypoint.sh"

env:
  HBF_HOST: sgroups{{ (split "sgroups-newman" .Helm.Release.Name)._1  }}
  REPORTER_DB_USER: user_rw
  REPORTER_DB_NAME: swarm
  REPORTER_DB_SCHEMA: hbf_api_results
  CI_PIPELINE_ID: "{{ .Helm.Custom.CiPipelineId }}"
  CI_MERGE_REQUEST_SOURCE_BRANCH_NAME: "{{ .Helm.Custom.CiMergeRequestSourceBranchName }}"
  CI_MERGE_REQUEST_TARGET_BRANCH_NAME: "{{ .Helm.Custom.CiMergeRequestTargetBranchName }}"
  TG_TOKEN: "{{ .Helm.Custom.TgToken }}"
  TG_GROUP_ID: "{{ .Helm.Custom.TgGroupId }}"
  HBF_IMAGE: "{{.Helm.Release.Image}}:{{.Helm.Release.Tag}}"
  POSTGRES_USER: user_admin
  POSTGRES_PASSWORD: swarm
  POSTGRES_DB: swarm 
  POSTGRES_HOST: postgres{{ (split "sgroups" .Helm.Release.Name)._1  }}
  POSTGRES_PORT: "5432"

job:
  backoffLimit: 0

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

config:
  subpath: entrypoint.sh
  path: /usr/src/hbf_api_tests
  data: |-
    #!/bin/bash

    export REPORTER_DB_USER=$REPORTER_DB_USER
    export REPORTER_DB_PWD=$REPORTER_DB_PWD
    export REPORTER_DB_HOST=$(echo $REPORTER_DB_HOST_PORT | awk -F ":" '{print $1}')
    export REPORTER_DB_PORT=$(echo $REPORTER_DB_HOST_PORT | awk -F ":" '{print $2}')
    export REPORTER_DB_NAME=$REPORTER_DB_NAME
    export REPORTER_DB_SCHEMA=$REPORTER_DB_SCHEMA

    exec node index.js
