imagePullSecrets:
  - name: harbor-swarm-registry-secret
  - name: harbor-registry-secret

image:
  repository: {{.Helm.Release.Image}}
  tag: {{.Helm.Release.Tag}}
  pullPolicy: IfNotPresent

service:
  ports:
    - port: 80
      name: http
      targetPort: 3000

ingress:
  enabled: true
  objects:
    - servicePort: 80
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
      - name: "{{ .Helm.Release.Namespace }}-ingress-controller.{{ .Helm.Release.Namespace }}.svc.{{ .Helm.Release.Cluster }}"
        path: /swarm_doc