command: [ "/bin/sh", "/app/entrypoint.sh"]

initContainers:
  migration:
    command:
      - "/bin/sh"
    args:
      - -c
      - exit 0
    image: harbor.wildberries.ru/docker-hub-proxy/library/alpine:3.16
    imagePullPolicy: IfNotPresent

config:
  path: /app
  files:
    entrypoint.sh:
      data: |-
        #!/bin/bash
        exec /app/bin/sgroups --config /app/config.yaml
