imagePullSecrets:
  - name: harbor-swarm-registry-secret
  - name: harbor-registry-secret

image:
  repository: harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-control
  tag: dev-f6d57694
  pullPolicy: IfNotPresent

vault:
  enabled: true
  env: [{}]
  entrypoint: "sh /app/entrypoint.sh"
  image:
    repository: harbor.wildberries.ru/docker-hub-proxy/library/vault
    tag: 1.8.1
    pullPolicy: IfNotPresent
  role: {{.Helm.Release.Namespace}}
  authPath: /auth/{{.Helm.Release.Cluster}}.vault-auth-per-cluster
  type: sidecar

job:
  backoffLimit: 0

restartPolicy: Never
annotations:
  cni.projectcalico.org/ipAddrs: "[\"29.64.0.231\"]"

labels:
  instance: p{{.Helm.Custom.CiPipelineId}}-abathur-control

extendedLabels:
  instance: p{{.Helm.Custom.CiPipelineId}}-abathur-control

config:
  version: v2
  files:
    entrypoint.sh:
      path: /app
      data: |
        #!/bin/bash
        exec node index.js

    config.properties:
      path: /usr/src/control/props
      data: |
        HBF_SERVER_REPOSITORY=harbor.wildberries.ru/swarm/swarm/swarm/sgroups/sgroups
        HBF_SERVER_TAG={{.Helm.Release.Tag}}

        HBF_CLIENT_REPOSITORY=harbor.wildberries.ru/swarm/swarm/swarm/sgroups/to-nft
        HBF_CLIENT_TAG={{.Helm.Release.Tag}}

        ABA_CLIENT_REPOSITORY=harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-client
        ABA_CLIENT_TAG=dev-f6d57694

        ABA_SERVER_REPOSITORY=harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-server
        ABA_SERVER_TAG=dev-f6d57694


        PIPELINE_ID={{.Helm.Custom.CiPipelineId}}
        JOB_ID={{.Helm.Custom.CiJobId}}
        NAMESPACE={{.Helm.Release.Namespace}}
        HBF_TAG={{.Helm.Release.Tag}}
        CI_SOURCE_BRANCH_NAME={{.Helm.Custom.CiSourceBranchName}}
        CI_TARGET_BRANCH_NAME=main
        COMMIT={{.Helm.Custom.Commit}}
        
        IS_DESTROY_AFTER=true

        F_HBF_SERVER_IP=29.64.0.232
        F_HBF_SERVER_PORT=9006

        A_HBF_SERVER_IP=29.64.0.233
        A_HBF_SERVER_PORT=9006

        HBF_REPORTER_PROTOCOL=http
        HBF_REPORTER_HOST=testops-ingress-controller.testops.svc.k8s.dldevel
        HBF_REPORTER_PORT=80

        API_REPORTER_PROTOCOL=http
        API_REPORTER_HOST=testops-ingress-controller.testops.svc.k8s.dldevel
        API_REPORTER_PORT=80

        ABA_CONTROL_IP=29.64.0.231
        ABA_CONTROL_PORT=9091
        ABA_PROXY_PROTOCOL=http
        ABA_PROXY_PORT=9092

        # 1-func 2-api 99-all
        SCENARIO=99
        TG_TOKEN=5996680756:AAGHDMu5WnkaVioGJbesVJMv8irooQvfL7g
        TG_GROUP_ID=-1001959123261

        API_TEST_REPOSITORY=harbor.wildberries.ru/swarm/swarm/testops/hbf_api_tests/sgroups-postman
        API_TEST_TAG=dev-e86aeae4
        API_TEST_IP=29.64.0.255

        ABA_SERVER_CPU=100m
        ABA_SERVER_MEM=500Mi
        ABA_CLIENT_CPU=100m
        ABA_CLIENT_MEM=500Mi
        HBF_SERVER_CPU=100m
        HBF_SERVER_MEM=100Mi
        HBF_CLIENT_CPU=100m
        HBF_CLIENT_MEM=100Mi
        API_TEST_CPU=300m
        API_TEST_MEM=300Mi

        DNS_IP=169.254.25.10
        DNS_PROTOCOL=udp
        DNS_PORT=53
