imagePullSecrets:
  - name: harbor-swarm-registry-secret
  - name: harbor-registry-secret

image:
  repository: harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-control
  tag: feature-delete-job-554eaa78
  pullPolicy: IfNotPresent

vault:
  enabled: true
  env: [{}]
  entrypoint: "sh /app/entrypoint.sh"
  image:
    repository: harbor.wildberries.ru/docker-hub-proxy/library/vault
    tag: 1.8.1
    pullPolicy: IfNotPresent
  role: {{.Helm.Release.Namespace}}
  authPath: /auth/{{.Helm.Release.Cluster}}.vault-auth-per-cluster
  type: sidecar

job:
  backoffLimit: 0

restartPolicy: Never
annotations:
  cni.projectcalico.org/ipAddrs: "[\"29.64.0.231\"]"

labels:
  instance: p{{.Helm.Custom.CiPipelineId}}-abathur-control

extendedLabels:
  instance: p{{.Helm.Custom.CiPipelineId}}-abathur-control

config:
  version: v2
  files:
    entrypoint.sh:
      path: /app
      data: |
        #!/bin/bash
        exec node index.js

    config.properties:
      path: /usr/src/control/props
      data: |
        HBF_SERVER_REPOSITORY=harbor.wildberries.ru/swarm/swarm/swarm/sgroups/sgroups
        HBF_SERVER_TAG={{.Helm.Release.Tag}}
        HBF_CLIENT_REPOSITORY=harbor.wildberries.ru/swarm/swarm/swarm/sgroups/to-nft
        HBF_CLIENT_TAG={{.Helm.Release.Tag}}
        ABA_CLIENT_REPOSITORY=harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-client
        ABA_CLIENT_TAG=feature-delete-job-554eaa78
        ABA_SERVER_REPOSITORY=harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-server
        ABA_SERVER_TAG=feature-delete-job-554eaa78
        PIPELINE_ID={{.Helm.Custom.CiPipelineId}}
        JOB_ID={{.Helm.Custom.CiJobId}}
        REPORTER_PROTOCOL=http
        REPORTER_HOST=10.36.46.222
        REPORTER_PORT=80
        NAMESPACE={{.Helm.Release.Namespace}}
        HBF_TAG={{.Helm.Release.Tag}}
        CI_SOURCE_BRANCH_NAME={{.Helm.Custom.CiSourceBranchName}}
        CI_TARGET_BRANCH_NAME=main
        COMMIT={{.Helm.Custom.Commit}}
        ABA_CONTROL_IP=29.64.0.231
        IS_DESTROY_AFTER=true

