env:
  SG_DB_PASSWORD: swarm
  SG_DB_URL: postgres{{ (split "sgroups" .Helm.Release.Name)._1  }}:5432

command:
  - "/bin/sh"
args:
  - /app/entrypoint.sh

initContainers:
  migration:
    env:
      - name: SG_DB_NAME
        value: swarm
      - name: SG_DB_USER
        value: user_admin
      - name: SG_DB_PASSWORD
        value: swarm
      - name: SG_DB_URL
        value: postgres{{ (split "sgroups" .Helm.Release.Name)._1  }}:5432

ingress:
  enabled: true
  objects:
    - servicePort: 80
      annotations:
        # nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
      - name: "{{ .Helm.Release.Namespace }}-ingress-controller.{{ .Helm.Release.Namespace }}.{{ .Helm.Release.Cluster }}"
        path: /
