name: Lint Go code

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'
      - run: go version    

      - name: Run Linter
        run: make lint
